# Generated by Django 3.0 on 2021-06-15 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_auto_20210517_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupToCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.Course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.Groups')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='studenttotask',
            name='grade',
        ),
        migrations.AddField(
            model_name='studenttotask',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentToCourse',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='moodle.Groups'),
        ),
    ]
